/**
 * Generates translations/options-all.js from export-all-lines.txt
 * Run: node scripts/generate-options.js
 */
const fs = require('fs');
const path = require('path');

const EXPORT = path.join(__dirname, 'export-all-lines.txt');
const OUT = path.join(__dirname, 'translations', 'options-all.js');

const PHRASES = [
  ['All of the above', 'Todas as anteriores'],
  ['All above', 'Todas as anteriores'],
  ['None of the Above', 'Nenhuma das anteriores'],
  ['None of the above', 'Nenhuma das anteriores'],
  ['Both of the above', 'Ambas as anteriores'],
  ['Both b and c', 'Ambas b e c'],
  ['True', 'Verdadeiro'],
  ['False', 'Falso'],
];

const TEXT_MAP = {
  '51mm, 63mm, 102mm': '51mm, 63mm, 102mm',
  '50mm, 70mm, 100mm': '50mm, 70mm, 100mm',
  '60mm, 80mm, 100mm': '60mm, 80mm, 100mm',
  '50mm, 80mm, 120mm': '50mm, 80mm, 120mm',
  '51mm': '51mm',
  '63mm': '63mm',
  '102mm': '102mm',
  '120mm': '120mm',
  '15mm': '15mm',
  '25mm': '25mm',
  '35mm': '35mm',
  '55mm': '55mm',
  '12.5mm': '12,5 mm',
  '9.5mm': '9,5 mm',
  '10mm': '10 mm',
  '13mm': '13 mm',
  '40mm': '40 mm',
  '50mm': '50 mm',
  '6.4 mm': '6,4 mm',
  '9.5 mm': '9,5 mm',
  '12 mm': '12 mm',
  '4 mm': '4 mm',
  'Standard Gypsum': 'Gesso Standard',
  'Moisture Resistant Board': 'Placa Resistente à Humidade',
  'Fire Resistant Board': 'Placa Resistente ao Fogo',
  'Soundproof Board': 'Placa Acústica',
  'To provide strength and clean corners': 'Proporcionar resistência e cantos limpos',
  'To increase soundproofing': 'Aumentar o isolamento acústico',
  'To hold the drywall in place': 'Manter o drywall no lugar',
  'To add decorative elements': 'Adicionar elementos decorativos',
  'Mineral Wool / Glass Wool': 'Lã Mineral / Lã de Vidro',
  'High Density Insulation': 'Isolamento de Alta Densidade',
  'To improve soundproofing by decoupling the drywall from the studs': 'Melhorar o isolamento acústico desacoplando o drywall dos montantes',
  'To provide additional fire resistance': 'Proporcionar resistência adicional ao fogo',
  'To support heavy items on the wall': 'Suportar objetos pesados na parede',
  'To reinforce the joints between drywall boards': 'Reforçar as juntas entre placas de drywall',
  'It is lightweight and easy to install': 'É leve e fácil de instalar',
  'It is resistant to rust and corrosion': 'É resistente à ferrugem e corrosão',
  'It is the most cost effective option': 'É a opção mais económica',
  'Single Layer Firewall': 'Parede Corta-Fogo de Camada Simples',
  'Double Layer Firewall': 'Parede Corta-Fogo de Dupla Camada',
  'Fire Rated Cavity Wall': 'Parede com Cavidade Classificada para Fogo',
  'Cement Board': 'Placa de Cimento',
  'High Density Plasterboard': 'Placa de Gesso de Alta Densidade',
  'Fire rated Gypsum Board': 'Placa de Gesso Classificada para Fogo',
  'Moisture & Fire Resistant Board': 'Placa Resistente à Humidade e ao Fogo',
  'Industrial or high risk areas': 'Áreas industriais ou de alto risco',
  'Residential homes': 'Habitações residenciais',
  'Offices': 'Escritórios',
  'Kitchens and bathrooms': 'Cozinhas e casas de banho',
  'Mineral Wool': 'Lã Mineral',
  'Glass Wool': 'Lã de Vidro',
  'Standard Gypsum Board': 'Placa de Gesso Standard',
  'Fire Rated Board': 'Placa Classificada para Fogo',
  'Sound & Load Resistant Boards': 'Placas Resistentes ao Som e à Carga',
  'They are suitable for areas exposed to high heat.': 'São adequadas para áreas expostas a calor elevado.',
  'They prevent mould and mildew growth in humid areas.': 'Previnem o crescimento de bolor e fungos em áreas húmidas.',
  'They are ideal for load bearing walls.': 'São ideais para paredes de carga.',
  'They improve sound transmission.': 'Melhoram a transmissão sonora.',
  'To prevent the spread of fire through joints and openings': 'Prevenir a propagação do fogo através de juntas e aberturas',
  'To add aesthetic appeal to the joints': 'Adicionar apelo estético às juntas',
  'To prevent moisture from entering the wall cavity': 'Prevenir a entrada de humidade na cavidade da parede',
  'To strengthen the overall wall structure': 'Reforçar a estrutura geral da parede',
  'Areas with heavy foot traffic': 'Áreas com elevado tráfego pedonal',
  'Areas that require both fire resistance and load bearing properties': 'Áreas que requerem resistência ao fogo e propriedades de carga',
  'Internal residential walls': 'Paredes interiores residenciais',
  'Wet areas like kitchens and bathrooms': 'Zonas húmidas como cozinhas e casas de banho',
  '400mm centres': '400 mm de centro a centro',
  '600mm centres': '600 mm de centro a centro',
  '800mm centres': '800 mm de centro a centro',
  '1000mm centres': '1000 mm de centro a centro',
  'To secure drywall boards to the studs': 'Fixar as placas de drywall aos montantes',
  'To add decorative elements to corners': 'Adicionar elementos decorativos aos cantos',
  'To insulate the cavity': 'Isolar a cavidade',
  'To cut drywall boards to size': 'Cortar as placas de drywall ao tamanho',
  'To drive screws quickly and efficiently into the studs': 'Apresentar parafusos de forma rápida e eficiente nos montantes',
  'To finish jointing and plastering': 'Concluir juntas e reboco',
  'To smooth the surface of the drywall boards': 'Alisar a superfície das placas de drywall',
  'Ensure the studs are spaced at the proper intervals': 'Garantir que os montantes estão espaçados nos intervalos corretos',
  'Secure the drywall boards tightly with screws': 'Fixar firmemente as placas de drywall com parafusos',
  'Install insulation for soundproofing or fire resistance if required': 'Instalar isolamento para isolamento acústico ou resistência ao fogo, se necessário',
  'Timber Skirting': 'Rodapé de Madeira',
  'Vinyl / Rubber Skirting': 'Rodapé de Vinil / Borracha',
  'Aluminium Skirting': 'Rodapé de Alumínio',
  'Tile Skirting': 'Rodapé de Azulejo',
  'Durability and hygiene': 'Durabilidade e higiene',
  'Aesthetic appeal': 'Apelo estético',
  'Low cost': 'Baixo custo',
  'Easy to install': 'Fácil de instalar',
  'Check that the drywall is securely anchored and level': 'Verificar se o drywall está firmemente ancorado e nivelado',
  'Ensure fire resistant boards are used in high risk areas': 'Garantir que placas resistentes ao fogo são utilizadas em áreas de alto risco',
  'Verify that all joints are smooth and no screw heads are visible': 'Verificar que todas as juntas estão lisas e que não são visíveis cabeças de parafuso',
  'To prevent cracks and improve strength': 'Prevenir fissuras e melhorar a resistência',
  'To enhance the aesthetic appeal': 'Melhorar o apelo estético',
  'To make the installation process easier': 'Facilitar o processo de instalação',
  'To reduce the overall weight of the wall': 'Reduzir o peso total da parede',
  'Decorative edge': 'Borda decorativa',
  'Support for insulation': 'Suporte para isolamento',
  'Primary load carrying structure': 'Estrutura principal de suporte de carga',
  'Joint tape': 'Fita de juntas',
  '300mm': '300 mm',
  '450mm': '450 mm',
  '600mm': '600 mm',
  '900mm': '900 mm',
  '25x25mm': '25x25 mm',
  '32x32mm': '32x32 mm',
  '50x50mm': '50x50 mm',
  '19x19mm': '19x19 mm',
  'Aluminium': 'Alumínio',
  'PVC': 'PVC',
  'Galvanised steel': 'Aço galvanizado',
  'Plywood': 'Contraplacado',
  'Mounting lights': 'Montagem de luminárias',
  'Enhancing acoustic performance': 'Melhorar o desempenho acústico',
  'Providing a neat finish at wall and ceiling junction': 'Proporcionar um acabamento limpo na junção parede-teto',
  'Acting as insulation support': 'Atuar como suporte de isolamento',
  'Polystyrene': 'Poliestireno',
  'Mineral wool': 'Lã mineral',
  'MDF': 'MDF',
  'Concrete tiles': 'Lajetas de betão',
  'Ceiling board': 'Placa de teto',
  'Soundproof insulation': 'Isolamento acústico',
  'Skimming plaster': 'Gesso de alisamento',
  'Steel stud': 'Montante de aço',
  'Support the ceiling': 'Suportar o teto',
  'Reinforce board joints': 'Reforçar juntas das placas',
  'Decorate the cornice': 'Decorar a cornija',
  'Seal wall angles': 'Selar cantoneiras de parede',
  'High material cost': 'Elevado custo de material',
  'Easy installation': 'Instalação fácil',
  'Thermal comfort': 'Conforto térmico',
  'Long construction time': 'Longo tempo de construção',
  'Aesthetic improvement': 'Melhoria estética',
  'A ceiling made of wood panels': 'Um teto feito de painéis de madeira',
  'A secondary ceiling installed below the main ceiling, supported by a metal framework': 'Um teto secundário instalado abaixo do teto principal, suportado por uma estrutura metálica',
  'A ceiling fixed directly to the structural ceiling': 'Um teto fixado diretamente ao teto estrutural',
  'A ceiling that is painted': 'Um teto que é pintado',
  'Plastic': 'Plástico',
  'Gypsum, mineral fibre, PVC, metal': 'Gesso, fibra mineral, PVC, metal',
  'Concrete': 'Betão',
  'Glass': 'Vidro',
  'To provide lighting integration': 'Proporcionar integração de iluminação',
  'To support the edges of the grid and secure it to the wall': 'Suportar as bordas da grelha e fixá-la à parede',
  'To conceal electrical wires': 'Ocultar fios elétricos',
  'To provide aesthetic appeal only': 'Proporcionar apelo estético apenas',
  '400mm x 400mm': '400 mm x 400 mm',
  '600mm x 600mm': '600 mm x 600 mm',
  '900mm x 900mm': '900 mm x 900 mm',
  '1200mm x 1200mm': '1200 mm x 1200 mm',
  'Gypsum Vinyl Faced': 'Gesso com Face de Vinil',
  'Mineral Fibre': 'Fibra Mineral',
  'PVC Tiles': 'Lajetas de PVC',
  'Metal Tiles': 'Lajetas Metálicas',
  'To hang the ceiling tiles in place': 'Pendurar as lajetas de teto no lugar',
  'To support the grid system by hanging it from the structural ceiling': 'Suportar o sistema de grelha pendurando-o do teto estrutural',
  'To lock the main and cross tees together': 'Bloquear os main tees e cross tees entre si',
  'To enhance the aesthetic design': 'Melhorar o design estético',
  'Wooden Tiles': 'Lajetas de Madeira',
  'Gypsum Vinyl Faced Tiles': 'Lajetas de Gesso com Face de Vinil',
  'Mineral Fibre Tiles': 'Lajetas de Fibra Mineral',
  '0.5 meters': '0,5 metros',
  '0.8 meters': '0,8 metros',
  '1.5 meters': '1,5 metros',
  '2 meters': '2 metros',
  'Suspension Wires': 'Fios de Suspensão',
  'Access Panels': 'Painéis de Acesso',
  'Connectors & Clips': 'Conectores e Clips',
  'Wall Angle': 'Cantoneira de Parede',
  'To provide natural lighting': 'Proporcionar iluminação natural',
  'To conceal electrical/data cables and enhance sound insulation': 'Ocultar cabos elétricos/dados e melhorar o isolamento acústico',
  'To create extra space for storage': 'Criar espaço extra para armazenamento',
  'To improve indoor air quality': 'Melhorar a qualidade do ar interior',
  'Region Settings': 'Definições de Região',
  'User Account Control': 'Controlo de Conta de Utilizador',
  'Power Settings': 'Definições de Energia',
  'Network and Sharing Settings': 'Definições de Rede e Partilha',
  'Updates': 'Atualizações',
  'Date Time Settings': 'Definições de Data e Hora',
  'Notepad ++': 'Notepad ++',
  'MySQL Server/Workbench': 'MySQL Server/Workbench',
  'Tight VNC': 'Tight VNC',
  'Teamviewer': 'TeamViewer',
  'Chrome': 'Chrome',
  'Stand Alone Store Or Head Office': 'Loja Autónoma ou Sede',
  'Lock Down Branch, Customers Created at Branch': 'Filial Bloqueada, Clientes Criados na Filial',
  'Franchize Branch, receive Stock Data from HO': 'Filial Franchise, recebe Dados de Stock da Sede',
  'Stand Alone (Update Listed Stores)': 'Autónomo (Atualizar Lojas Listadas)',
  'Region settings': 'Definições de região',
  'Store Setup': 'Configuração de Loja',
  'Company Parameters': 'Parâmetros da Empresa',
  'User Setup': 'Configuração de Utilizador',
  'Microsoft Exchange': 'Microsoft Exchange',
  'legend1501': 'legend1501',
  'Legend@1501': 'Legend@1501',
  'Legend1501': 'Legend1501',
  'LEGEND@1501': 'LEGEND@1501',
  'Edit - Stores': 'Editar - Lojas',
  'Settings - Stores Edit': 'Definições - Editar Lojas',
  'Edit - Inventory - Stores': 'Editar - Inventário - Lojas',
  'Localhost': 'Localhost',
  'Online MySQL Server': 'Servidor MySQL Online',
  'Access DB': 'Base de Dados Access',
  'Stud Only': 'Apenas Montante',
  'Steel stud track plus two layers of board': 'Trilho de montante de aço mais duas camadas de placa',
  'Stud and insulation': 'Montante e isolamento',
  'Stud and plaster finish only': 'Apenas montante e acabamento em gesso',
  'Increase fire resistance': 'Aumentar a resistência ao fogo',
  'Support the board': 'Suportar a placa',
  'Provide clean, durable edge protection': 'Proporcionar proteção de borda limpa e durável',
  'Reduce wall thickness': 'Reduzir a espessura da parede',
  'Wall length': 'Comprimento da parede',
  'Board thickness only': 'Apenas espessura da placa',
  'Stud gauge, height, and applied loads': 'Calibre do montante, altura e cargas aplicadas',
  'Door width': 'Largura da porta',
  'Standard studs only': 'Apenas montantes standard',
  'Timber packing only': 'Apenas enchimento de madeira',
  'Reinforced jamb studs and a head track ': 'Montantes de ombreira reforçados e um trilho superior',
  'Extra plaster': 'Gesso extra',
  'Increased acoustic rating': 'Classificação acústica aumentada',
  'Reduced fire rating': 'Classificação de fogo reduzida',
  'Load transfer above the opening': 'Transferência de carga acima da abertura',
  'Paint adhesion issues': 'Problemas de aderência da tinta',
  'Reduce cost': 'Reduzir o custo',
  'Improve aesthetics only': 'Melhorar apenas a estética',
  'Accommodate building movement': 'Acomodar movimentos do edifício',
  'Support aluminium trims': 'Suportar cantoneiras de alumínio',
  'Fire': 'Fogo',
  'Impact': 'Impacto',
  'Corrosion': 'Corrosão',
  'Noise': 'Ruído',
  'Random screw spacing': 'Espaçamento aleatório de parafusos',
  'Correct edge distances and screw spacing': 'Distâncias corretas de borda e espaçamento de parafusos',
  'Over-tightened screws': 'Parafusos demasiado apertados',
  'Screws through aluminium trims': 'Parafusos através de cantoneiras de alumínio',
  'Board thickness alone': 'Apenas espessura da placa',
  'Stud size only': 'Apenas tamanho do montante',
  'A tested and approved system assembly': 'Um conjunto de sistema testado e aprovado',
  'Paint specification': 'Especificação de tinta',
  'Better paint finish': 'Melhor acabamento de tinta',
  'Reduced stud spacing': 'Espaçamento reduzido dos montantes',
  'Bigger Studs multiple board layers and insulation': 'Montantes maiores, múltiplas camadas de placa e isolamento',
  'Lower fire resistance': 'Menor resistência ao fogo',
  'Structural strength': 'Resistência estrutural',
  'Fire and acoustic performance resistance': 'Resistência ao desempenho de fogo e acústico',
  'Impact resistance': 'Resistência ao impacto',
  'Moisture control': 'Controlo de humidade',
  'Wrong stud gauge': 'Calibre de montante incorreto',
  'Incorrect board thickness': 'Espessura de placa incorreta',
  'Unsealed penetrations and joints': 'Penetrações e juntas não seladas',
  'Excess insulation': 'Isolamento em excesso',
  'With adhesive only': 'Apenas com adesivo',
  'As per tested fixing pattern': 'Conforme padrão de fixação testado',
  'Randomly fixing pattern': 'Padrão de fixação aleatório',
  'with Teck screws ': 'com parafusos Teck',
  'Fire-stopped with approved materials': 'Cortado-fogo com materiais aprovados',
  'Painted only': 'Apenas pintado',
  'Left Open': 'Deixado Aberto',
  'Covered with trims': 'Coberto com cantoneiras',
  'Be oversized': 'Ser sobredimensionado',
  'Be boxed in only': 'Ser apenas encaixotado',
  'Avoid insulation': 'Evitar isolamento',
  'Maintain the full fire rating by using Intumescent Sealant.': 'Manter a classificação de fogo completa utilizando Selante Intumescente.',
  'Paint quality': 'Qualidade da tinta',
  'Movement joints and structural supports at 5-meter intervals or detailing': 'Juntas de movimento e suportes estruturais a intervalos de 5 metros ou detalhamento',
  'Door detailing ': 'Detalhamento de porta',
  'Tile adhesive selection': 'Seleção de adesivo para azulejos',
  'Heavy applied load stud spacing must be smaller.': 'Carga aplicada pesada – o espaçamento dos montantes deve ser menor.',
  'Medium finish': 'Acabamento médio',
  'Light finish ': 'Acabamento leve',
  'Structural load': 'Carga estrutural',
  'Standard gypsum board': 'Placa de gesso standard',
  'Fire-rated board': 'Placa classificada para fogo',
  'Moisture-resistant / cementitious board': 'Placa resistente à humidade / cimentícia',
  'Acoustic board': 'Placa acústica',
  'Reduced to limit deflection 600 mm centres': 'Reduzido para limitar deflexão – 600 mm de centro a centro',
  '500 mm centres': '500 mm de centro a centro',
  '400 mm Centres': '400 mm de centro a centro',
  'Increased for strength': 'Aumentado para resistência',
  'Better bonding': 'Melhor aderência',
  'Lower cost': 'Menor custo',
  'Tile cracking and grout failure': 'Fissuras nos azulejos e falha do grout',
  'Improved waterproofing': 'Impermeabilização melhorada',
  'Over tiles only': 'Apenas sobre azulejos',
  'Under studs': 'Sob os montantes',
  'Behind tiles and at wet zones': 'Por detrás dos azulejos e em zonas húmidas',
  'At ceiling level': 'Ao nível do teto',
  'Tile colour': 'Cor do azulejo',
  'Stud gauge': 'Calibre do montante',
  'Wall height only': 'Apenas altura da parede',
  'Substrate type and tile weight ': 'Tipo de substrato e peso do azulejo',
  'Fixed to boards only': 'Fixado apenas às placas',
  'Adhesive mounted': 'Montado com adesivo',
  'Anchored to reinforced studs or noggings': 'Ancorado a montantes reforçados ou noggings',
  'Screwed through tiles': 'Parafusado através dos azulejos',
  'Inadequate waterproofing detailing ': 'Detalhamento de impermeabilização inadequado',
  'Heavy tiles': 'Azulejos pesados',
  'Poor paint': 'Tinta de má qualidade',
  'Galvanised studs': 'Montantes galvanizados',
  'Sound': 'Som',
  'Point loads from cabinets and counters': 'Cargas pontuais de armários e bancadas',
  'Wind loads': 'Cargas de vento',
  'Thicker boards only': 'Apenas placas mais espessas',
  'Structural backing or reinforced studs': 'Reforço estrutural ou montantes reforçados',
  'Adhesive fixing': 'Fixação com adesivo',
  'Improve load capacity': 'Melhorar capacidade de carga',
  'Be acceptable short term': 'Ser aceitável a curto prazo',
  'Led to pull-out failure': 'Levar a falha por arrancamento',
  'Improve acoustics': 'Melhorar acústica',
  'Tile, glass, or protected board systems': 'Sistemas de azulejo, vidro ou placa protegida',
  'Wallpaper': 'Papel de parede',
  'Standard paint': 'Tinta standard',
  'Acoustic panels': 'Painéis acústicos',
  'Wall colour': 'Cor da parede',
  'Ceiling height': 'Altura do teto',
  'Applied loads from cabinetry': 'Cargas aplicadas de armários',
  'Door position': 'Posição da porta',
  'Improved alignment': 'Melhor alinhamento',
  'No issues': 'Sem problemas',
  'Cracking of finishes and joint failure': 'Fissuras nos acabamentos e falha das juntas',
  'Better load sharing': 'Melhor partilha de carga',
  'Unprotected': 'Desprotegido',
  'Installed after cabinets ': 'Instalado após armários',
  'Coordinated before board installation': 'Coordenado antes da instalação das placas',
  'Surface mounted': 'Montado à superfície',
  'Verification of backing and fixing zones': 'Verificação das zonas de reforço e fixação',
  'Trims installation': 'Instalação de cantoneiras',
  'Painting': 'Pintura',
  'Tile delivery': 'Entrega de azulejos',
  'Hang directly from main tee without reinforcement': 'Pendurar diretamente do main tee sem reforço',
  'Provide local reinforcement to the main tee with a dedicated hanger to structure': 'Proporcionar reforço local ao main tee com um suspensor dedicado à estrutura',
  'Increase cross tee density to 400 mm centres': 'Aumentar a densidade das cross tees para 400 mm de centro a centro',
  'Replace main tee with 35 mm plaster grid': 'Substituir main tee por grelha de gesso de 35 mm',
  '300 mm ': '300 mm',
  '1200 mm': '1200 mm',
  '400 mm': '400 mm',
  'Single 15 mm layer with intumescent paint': 'Camada única de 15 mm com tinta intumescente',
  'Two staggered 15 mm layers with independent fixings': 'Duas camadas escalonadas de 15 mm com fixações independentes',
  'One 12 mm and one 15 mm layer fixed together': 'Uma camada de 12 mm e uma de 15 mm fixadas juntas',
  'Three 9 mm layers fixed to timber battens': 'Três camadas de 9 mm fixadas a ripas de madeira',
  '1500 mm': '1500 mm',
  '95 mm ': '95 mm',
  '112 mm': '112 mm',
  '115 mm': '115 mm',
  '123 mm': '123 mm',
  '10 kg/m²': '10 kg/m²',
  '20 kg/m²': '20 kg/m²',
  '30 kg/m² ': '30 kg/m²',
  '40 kg/m²': '40 kg/m²',
  '150 mm': '150 mm',
  '300 mm': '300 mm',
  'Intumescent putty pack sized and installed to manufacturer instructions plugs only': 'Pacote de massa intumescente dimensionado e instalado conforme instruções do fabricante – apenas tampões',
  'Mineral wool plugs only': 'Apenas tampões de lã mineral',
  'Standard silicone sealant': 'Selante de silicone standard',
  'Cementitious grout': 'Grout cimentício',
  'Single 15 mm layer only': 'Apenas camada única de 15 mm',
  'Two staggered 15 mm layers fixed independently to angles': 'Duas camadas escalonadas de 15 mm fixadas independentemente às cantoneiras',
  'Three 9 mm layers with timber battens': 'Três camadas de 9 mm com ripas de madeira',
  '10 mm': '10 mm',
  '26 kg/m² ': '26 kg/m²',
  'Airborne sound': 'Som aéreo',
  'Structure borne sound': 'Som estrutural',
  'Flanking sound': 'Som flanking',
  'Thermal sound': 'Som térmico',
  'Only the joints of drywall': 'Apenas as juntas do drywall',
  'The entire wall surface': 'Toda a superfície da parede',
  'Screw holes only': 'Apenas furos de parafuso',
  'Corners only': 'Apenas cantos',
  'Covering whole walls': 'Cobrir paredes inteiras',
  'Priming plaster': 'Gesso de primagem',
  'Painting surfaces': 'Pintar superfícies',
  'Filling seams and screw holes in drywall ': 'Preencher juntas e furos de parafuso em drywall',
  '1 mm': '1 mm',
  '2–4 mm': '2–4 mm',
  '20 mm': '20 mm',
  'Steel trowel': 'Espátula de aço',
  'Paint roller': 'Rolo de pintura',
  'Sandpaper': 'Lixa',
  'Hammer': 'Martelo',
  'Nails': 'Pregos',
  'Tape': 'Fita',
  'Screws': 'Parafusos',
  'Primer': 'Primário',
  'Painted immediately': 'Pintado imediatamente',
  'Washed with water': 'Lavado com água',
  'Sanded smooth': 'Lixado até ficar liso',
  'Covered with skim plaster': 'Coberto com gesso de alisamento',
  'Mixing with water': 'Mistura com água',
  'Sanding after drying': 'Lixar após secagem',
  'Using a trowel': 'Utilizar uma espátula',
  'Drying before painting': 'Secagem antes de pintar',
  'The creamy surface layer removed with a rubber trowel': 'A camada superficial cremosa removida com espátula de borracha',
  'The powder before mixing': 'O pó antes da mistura',
  'The water content in plaster': 'O teor de água no gesso',
  'The primer applied before painting': 'O primário aplicado antes de pintar',
  'One': 'Uma',
  'Two (tape, fill, finish)': 'Duas (fita, preenchimento, acabamento)',
  'Three': 'Três',
  'Four': 'Quatro',
  'Jointing compound': 'Massa de juntas',
  'Paint': 'Tinta',
  'Supporting and fixing the plasterboard ceiling': 'Suportar e fixar o teto em placa de gesso',
  'Supporting the roof structure': 'Suportar a estrutura do telhado',
  'Decorative and neatness': 'Decorativo e aspeto limpo',
  'Holding insulation only': 'Apenas suportar isolamento',
  'Perimeter finishing': 'Acabamento perimetral',
  'Reinforcing ceiling joints': 'Reforçar juntas do teto',
  'To be painted': 'Para ser pintado',
  'Decorative moulding': 'Moldagem decorativa',
  'Prevent ceiling sagging and cracking': 'Prevenir afundamento e fissuras no teto',
  'Improve soundproofing': 'Melhorar isolamento acústico',
  'Reduce material cost': 'Reduzir custo de material',
  'Increase ceiling height': 'Aumentar altura do teto',
  'Structural support': 'Suporte estrutural',
  'Decorative transition between wall and ceiling': 'Transição decorativa entre parede e teto',
  'Ventilation': 'Ventilação',
  'Lighting support': 'Suporte de iluminação',
  'Wood screws': 'Parafusos de madeira',
  'Drywall screws': 'Parafusos de drywall',
  'Clue': 'Cola',
  'Cracking and visible joint lines': 'Fissuras e linhas de junta visíveis',
  'Moisture buildup': 'Acumulação de humidade',
  'Flanking noise': 'Ruído flanking',
  'Fire damage': 'Danos por fogo',
  'Washed/cleaned': 'Lavado/limpo',
  'Smooth, filled, and sanded': 'Liso, preenchido e lixado',
  'Oiled/sanded': 'Oleado/lixado',
  'Left untreated': 'Deixado sem tratamento',
  'Cross tees': 'Cross tees',
  'To screw the boards on': 'Para aparafusar as placas',
  'Main tees': 'Main tees',
  'perimeter trims': 'cantoneiras perimetrais',
  'Support lighting only': 'Suportar apenas iluminação',
  'Form the ceiling grid structure': 'Formar a estrutura da grelha do teto',
  'Fix perimeter trim': 'Fixar cantoneira perimetral',
  'Support walls': 'Suportar paredes',
  'Seamless Ceiling': 'Teto Contínuo',
  'Ceiling joints are fully plastered smooth': 'As juntas do teto são totalmente rebocadas e lisas',
  'Tiles are removable': 'As lajetas são removíveis',
  'Ceiling is exposed': 'O teto está exposto',
  'Hold ceiling tiles': 'Segurar lajetas de teto',
  'Hide electrical wiring': 'Ocultar cablagem elétrica',
  'Create a clean finished edge at walls': 'Criar uma borda acabada e limpa nas paredes',
  'Ceiling is 3 m thick': 'O teto tem 3 m de espessura',
  'Distance between slab and ceiling is 3 m': 'A distância entre a laje e o teto é de 3 m',
  'Ceiling height is 3 m': 'A altura do teto é de 3 m',
  'Void is filled with concrete': 'O vazio está preenchido com betão',
  'Moister': 'Humidade',
  'Airborne noise': 'Ruído aéreo',
  'Uneven ceiling finish': 'Acabamento de teto irregular',
  'Joints to open up.': 'Juntas a abrirem.',
  'Paint the boards': 'Pintar as placas',
  'Ensure boards are securely fixed': 'Garantir que as placas estão firmemente fixadas',
  'Install lights': 'Instalar luminárias',
  'Instal extra brandering': 'Instalar brandering extra',
  'Aluminium Head Channel': 'Canal Superior de Alumínio',
  'Timber Brandering': 'Brandering de Madeira',
  'Shadowline wall trim': 'Cantoneira de parede Shadowline',
  '76 mm Cove Corners': 'Cantos Cove de 76 mm',
  'Moulded Cove corners.': 'Cantos cove moldados.',
  '3.600 mm': '3.600 mm',
  '2.700 mm': '2.700 mm',
  '3.00 mm': '3,00 mm',
  'Solid plaster ceilings': 'Tetos em gesso sólido',
  'Wall partitions': 'Divisórias',
  'Roofing structures': 'Estruturas de cobertura',
  'Lay-in ceiling tile systems': 'Sistemas de lajetas de teto lay-in',
  '600 mm x 1200 mm': '600 mm x 1200 mm',
  'Reduce ceiling height': 'Reduzir altura do teto',
  'Create a recessed shadow gap at the wall': 'Criar um vão sombreado reentrante na parede',
  'Hide ducting': 'Ocultar condutas',
  'Fixing Plaster boards ': 'Fixação de placas de gesso',
  'Removable for access to services': 'Removível para acesso a serviços',
  'Fixed permanently': 'Fixado permanentemente',
  'Nailed to the grid': 'Pregado à grelha',
  'Painted before installation': 'Pintado antes da instalação',
  'Use 25 mm Drywall screw': 'Utilizar parafuso de drywall de 25 mm',
  '50 x 20 Galv Angle': 'Cantoneira Galv 50 x 20',
  'Suspension wires or hangers': 'Fios de suspensão ou suspensores',
  'Wall angles only': 'Apenas cantoneiras de parede',
  'Use Griping Tool': 'Utilizar ferramenta de aperto',
  'Decoration only': 'Apenas decoração',
  'Structural beams': 'Vigas estruturais',
  'Easy access': 'Acesso fácil',
  'Services like lights, air-conditioning, and cables': 'Serviços como iluminação, ar condicionado e cabos',
  'The grid is level and square': 'A grelha está nivelada e quadrada',
  'Electrical testing': 'Testes elétricos',
  'Wall plastering': 'Reboco de parede',
  'Fire resistance': 'Resistência ao fogo',
  'Easy access for maintenance': 'Acesso fácil para manutenção',
  'Heavy load capacity': 'Elevada capacidade de carga',
  'Acoustics': 'Acústica',
  'A. 600 mm': 'A. 600 mm',
  'Plaster trim': 'Plaster trim',
  'Shadowline Wall Angle': 'Cantoneira de Parede Shadowline',
  'None': 'Nenhum',
  'B & C': 'B e C',
  'Just in Special Ceilings': 'Apenas em Tetos Especiais',
  'For Security': 'Para Segurança',
  'Easy access ': 'Acesso fácil',
  'Go': 'Go',
  'Gd': 'Gd',
  'Au': 'Au',
  'Ag': 'Ag',
  'Vincent van gogh': 'Vincent van Gogh',
  'Pablo Picasso': 'Pablo Picasso',
  'Leonardo Da Vinci': 'Leonardo Da Vinci',
  'Michaelangelo': 'Michelangelo',
  'Central Processing unit': 'Central Processing Unit',
  'Computer Personal Unit': 'Computer Personal Unit',
  'Control Processing Utility': 'Control Processing Utility',
  'Core Power Unit': 'Core Power Unit',
  '2005': '2005',
  '2007': '2007',
  '2009': '2009',
  '2011': '2011',
  'mars': 'Marte',
  'Saturn': 'Saturno',
  'Jupiter': 'Júpiter',
  'Neptune': 'Neptuno',
  'gold': 'ouro',
  'iron': 'ferro',
  'diamond': 'diamante',
  'platinum': 'platina',
  'Fe': 'Fe',
  'Cu': 'Cu',
  'Mars': 'Marte',
  'Venus': 'Vénus',
  'Earth': 'Terra',
  'Nucleus': 'Núcleo',
  'Ribosome': 'Ribossoma',
  'Mitochondria': 'Mitocôndria',
  'Golgi apparatus': 'Aparato de Golgi',
  '300,000 km/s': '300 000 km/s',
  '150,000 km/s': '150 000 km/s',
  '1,000,000 km/s': '1 000 000 km/s',
  '30,000 km/s': '30 000 km/s',
  'Oxygen': 'Oxigénio',
  'Carbon dioxide': 'Dióxido de carbono',
  'Nitrogen': 'Azoto',
  'Argon': 'Árgon',
  'Metal Tiles': 'Lajetas Metálicas',
  'Aluminium trims': 'Cantoneiras de alumínio',
  '600 mm': '600 mm',
  '900 mm': '900 mm',
  '25 mm': '25 mm',
  '50 mm': '50 mm',
  '15 mm': '15 mm',
  '12.5 mm': '12,5 mm',
  'All': 'Todas',
  'Support insulation': 'Suportar isolamento',
  'Support lighting': 'Suportar iluminação',
  'Painting the room': 'Pintar a divisão',
  'Easy to decorate': 'Fácil de decorar',
};

function translateOption(text) {
  if (TEXT_MAP[text] !== undefined) return TEXT_MAP[text];
  const t = text.trim();
  for (const [en, pt] of PHRASES) {
    if (t === en) return pt;
  }
  if (TEXT_MAP[t] !== undefined) return TEXT_MAP[t];
  throw new Error(`Missing translation for option text: "${text}"`);
}

const lines = fs.readFileSync(EXPORT, 'utf8').split('\n');
const options = {};
const missing = [];

for (const line of lines) {
  if (!line.startsWith('O')) continue;
  const m = line.match(/^O(\d+)\|q:\d+\|text:"((?:[^"\\]|\\.)*)"$/);
  if (!m) continue;
  const [, id, text] = m;
  const src = text.replace(/\\"/g, '"');
  try {
    options[id] = { optionText: translateOption(src) };
  } catch (e) {
    missing.push({ id, text: src });
  }
}

if (missing.length) {
  console.error('Missing translations:', missing.length);
  missing.forEach((x) => console.error(`  O${x.id}: "${x.text}"`));
  process.exit(1);
}

const body = 'module.exports = ' + JSON.stringify(options, null, 2) + ';\n';
fs.writeFileSync(OUT, body, 'utf8');
console.log('Written', OUT, 'with', Object.keys(options).length, 'options');
