-- Import users from userBranchesAndWorkTypes.csv
-- Step 1: add username column (or run migration 1740700000000-AddUserUsernameColumn)
-- Step 2: backfill usernames for existing MySQL users
-- Step 3: insert new users with username
-- Temporary password for new users: ProTrain@2026
-- Review before running in production.

START TRANSACTION;

ALTER TABLE `users`
ADD COLUMN `username` varchar(255) NULL;

CREATE UNIQUE INDEX `IDX_USER_USERNAME` ON `users` (`username`);

-- Backfill usernames for 37 existing users matched from CSV
UPDATE users SET username = 'prudence', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('prudencelencwe76@gmail.com'); -- CSV: prudencelencwe76@gmail.com
UPDATE users SET username = 'fanyane', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('mofokengfanyane74@gmail.com'); -- CSV: mofokengfanyane74@gmail.com
UPDATE users SET username = 'thabo', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('bethlehem@bitgroup.co.za'); -- CSV: bethlehem@bitgroup.co.za
UPDATE users SET username = 'roberto', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('roberto.barradas@bitgroup.co.za'); -- CSV: roberto.barradas@bitgroup.co.za
UPDATE users SET username = 'sandra', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('sales21@bitgroup.co.za'); -- CSV: sales21@legendsystems.co.za
UPDATE users SET username = 'julian', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('julian.diviani@bitgroup.co.za'); -- CSV: julian@bitgroup.co.za
UPDATE users SET username = 'vitor', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('vitor.medeiros@bitgroup.co.za'); -- CSV: vitor.medeiros@bitgroup.co.za
UPDATE users SET username = 'riaan', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Bitsales@bitgroup.co.za'); -- CSV: bitsales@bitgroup.co.za
UPDATE users SET username = 'cebo', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('sales5@bitgroup.co.za'); -- CSV: sales5@bitgroup.co.za
UPDATE users SET username = 'bmzobe', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('RichardsBay@bitgroup.co.za'); -- CSV: richardsbay@bitgroup.co.za
UPDATE users SET username = 'felex', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('felex.ndlovu@bitgroup.co.za'); -- CSV: fht.quality@gmail.com
UPDATE users SET username = 'brandono', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('brandon.olifant@legendsystems.co.za'); -- CSV: brandonolifant10@gmail.com
UPDATE users SET username = 'tjaart', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('tjaart.pretorius@bitgroup.co.za'); -- CSV: tjaart.pretorius@bitgroup.co.za
UPDATE users SET username = 'ruben', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('ruben.tavares@bitgroup.co.za'); -- CSV: ruben@bitgroup.co.za
UPDATE users SET username = 'patrickv', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('mosesvilakazi17@gmail.com'); -- CSV: mosesvilakazi17@gmail.com
UPDATE users SET username = 'benz', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('bilal.mahomed@bitgroup.co.za'); -- CSV: ben@bitgroup.co.za
UPDATE users SET username = 'lynette', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('lynettebanda03@gmail.com'); -- CSV: lynettebanda03@gmail.com
UPDATE users SET username = 'vuyo', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('emalahleni@bitgroup.co.za'); -- CSV: emalahleni@bitgroup.co.za
UPDATE users SET username = 'yorrick', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('yorrick.kruger@bitgroup.co.za'); -- CSV: yorrick.kruger@bitgroup.co.za
UPDATE users SET username = 'tumi', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('stuurmantumi41@gmail.com'); -- CSV: stuurmantumi41@gmail.com
UPDATE users SET username = 'sidney', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('burgersfort1@bitgroup.co.za'); -- CSV: burgersfort1@bitgroup.co.za
UPDATE users SET username = 'jeandre', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('jeandre.bouwer@bitgroup.co.za'); -- CSV: jeandreb12345@icloud.com
UPDATE users SET username = 'nelson', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('nelson.matsinhe@bitgroup.co.za'); -- CSV: nelson.matsinhe@bitgroup.co.za
UPDATE users SET username = 'junior', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('giyani@bitgroup.co.za'); -- CSV: giyani@bitgroup.co.za
UPDATE users SET username = 'dakalo', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('louistrichardt@bitgroup.co.za'); -- CSV: lavhelesanidakalo@gmail.com
UPDATE users SET username = 'thoriso', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('mahikeng@bitgroup.co.za'); -- CSV: thoriso@legendsystems.co.za
UPDATE users SET username = 'genop', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Midrand2@bitgroup.co.za'); -- CSV: midrand2@bitgroup.co.za
UPDATE users SET username = 'penny', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('penny@bitgroup.co.za'); -- CSV: penny@gmail.com
UPDATE users SET username = 'mackm', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('mokopane2@bitgroup.co.za'); -- CSV: mokopane2@bitgroup.co.za
UPDATE users SET username = 'innocent', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('inocent.livhalani@bitgroup.co.za'); -- CSV: inocent.livhalani@bitgroup.co.za
UPDATE users SET username = 'ashley', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Ashley.S@bitgroup.co.za'); -- CSV: ashley.stone020972@gmail.com
UPDATE users SET username = 'snethemba', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('soweto@bitgroup.co.za'); -- CSV: soweto@bitgroup.co.za
UPDATE users SET username = 'patrickm', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Patrick@bitgroup.co.za'); -- CSV: patrick@bitgroup.co.za
UPDATE users SET username = 'andrew', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Rustenburg@bitgroup.co.za'); -- CSV: rustenburg@bitgroup.co.za
UPDATE users SET username = 'siya', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Southgate@bitgroup.co.za'); -- CSV: southgate@bitgroup.co.za
UPDATE users SET username = 'tendani', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('Thohoyando@bitgroup.co.za'); -- CSV: thohoyando@bitgroup.co.za
UPDATE users SET username = 'melvin', updatedAt = CURRENT_TIMESTAMP(6) WHERE LOWER(email) = LOWER('tzaneen@bitgroup.co.za'); -- CSV: tzaneen@bitgroup.co.za

-- Insert 84 new users
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('f620330a-20b5-44dc-bb1b-aa27a40e27f5', 'thabog@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Thabo', 'Gabosimologe', 'thabog', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '269ee44d-2767-474c-a48c-383bff7d0427'); -- thabog / BitGaborone
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('433dbc17-fb85-4b64-97a1-4744cbba258a', 'sales30@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Tshenolo', 'Galetswegope', 'tshenolo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '269ee44d-2767-474c-a48c-383bff7d0427'); -- tshenolo / BitGaborone
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('296bae78-2ae5-4872-a235-9bae48462c82', 'tumiso@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Tumiso', 'Maswabi', 'tumiso', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '269ee44d-2767-474c-a48c-383bff7d0427'); -- tumiso / BitGaborone
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('c1102083-7018-46d2-acdd-00f83d32192d', 'hugo.azeredo@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Hugo Amaro', 'Azeredo', 'hugo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- hugo / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e149d8fb-3347-4a20-a1f6-d3c2128e3b40', 'lindelanizweli543@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Lindelani Zweli', 'Buthelezi', 'lindelani', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- lindelani / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('389f51a8-aa18-437a-87b7-8527dfc85735', 'garycalaca@ymail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Gary', 'Calaca', 'gary', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- gary / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e3d6c14f-3879-4efa-834c-68eab8d28680', 'jackiecampher61@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Jackie', 'Campher', 'jackie', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- jackie / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e48abaad-fe02-48eb-9e23-d0544ce35991', 'sdladla0216@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Simphiwe', 'Dladla', 'simphiwe', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- simphiwe / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('0426f884-fd59-4041-93fb-fc4b3de18d62', 'nn@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Ntobeko', 'Khanyile', 'ntobeko', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- ntobeko / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('9c73aba4-39a0-4bd4-9040-a322a6c8b7ab', 'kinneard65@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Diane', 'Kinnear', 'diane', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- diane / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('12039dd2-009c-4883-b33b-c12185d907a4', 'chilton.lau@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Chilton Warrick', 'Lau', 'chilton', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- chilton / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('23d7084d-e89d-4d79-b453-1976e341c8ef', 'siviwe.madikane@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Siviwe', 'Madikane', 'siviwe', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- siviwe / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('d0f0ae73-d28f-4fa1-8595-b23e8b28dca0', 'khulumani@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Khulumani', 'Mazibuko', 'khulumani', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- khulumani / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('3007c6ab-db91-412e-ba7a-925fcef86571', 'sihlemba301@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sihle', 'Mbatha', 'sihle', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sihle / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('cba80127-4f0f-4c00-8c6f-9bd658cf008f', 'meinietanica@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Tanica', 'Meinie', 'tanica', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- tanica / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('0b31e596-9d0b-4bc7-811d-d680504ad29c', 'bongumusajunior@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Bongumusa', 'Miya', 'bongumusa', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- bongumusa / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('fcdb02d4-92d1-404c-bb63-ddb67b3bd9fb', 'sm@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sibonakaliso', 'Mkhize', 'sibonakaliso', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sibonakaliso / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('f7736d66-201d-4da4-a7cb-6395f4042275', 'thokozanimkhize98@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Thokozani', 'Mkhize', 'thokozani', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- thokozani / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('683dde30-0035-467d-9fa2-192dbc15783a', 'marg@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Margarida', 'Morehen', 'marg', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- marg / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('2b995cfd-3fbd-4439-9905-655612d64f66', 'atmorongoa@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Alois', 'Morongoa', 'alois', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- alois / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('1e5f5c36-c37c-42b3-95e6-236e2642f80f', 'mgababamomothoana@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'karabo', 'Motlhoana', 'karabo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- karabo / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('41b14600-e698-4b33-839c-592e8bd52107', 'innocentmthembu744@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Innocent Mkhawuleni', 'Mthembu', 'mthembu', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- mthembu / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('29193362-2090-437d-ba3d-5a931d382128', 'snnnm@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sboniso', 'Mthethwa', 'sboniso', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sboniso / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('f6e2a23a-45b0-4604-bdf0-fa8954ccb39b', 'bmunthri@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Bonita', 'Munthri', 'bonita', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- bonita / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('a93df07a-b473-41a9-9ff7-1e9bb1e9e73a', 'avelancontsa05@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Avela', 'Ncontsa', 'avela', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- avela / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('b28a64ae-3f9c-4a67-a08e-b7e57ce32ac8', 'josiphat@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Josiphat', 'Ndlovu', 'josiphat', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- josiphat / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('3f4ac221-8705-45d3-8d6c-621e8969bb40', 'mngubane@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Mthobisi', 'Ngubane', 'mngubane', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- mngubane / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('7fa7f8d8-9d1a-45a7-919b-ca49ce107c8b', 'patngubane549@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Patrick', 'Ngubane', 'patrick', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- patrick / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e3ec6b73-1c63-4e10-8dde-212ffafb60d5', 'jabungwenya@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Jabu', 'Ngwenya', 'jabu', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- jabu / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('c88c15fc-ff76-4173-ab5d-70c7ef4b6a00', 'sakhileian89@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Ian sakhile', 'Nkosi', 'sakhile', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sakhile / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('2f96ee24-40de-434b-a9a9-38cac14119da', 'sandintuli@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sandile', 'Ntuli', 'sandile', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sandile / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('ce327757-3daf-4817-881d-44c842fb5553', 'sanet@fusechem.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sanet', 'Oelofse', 'sanet', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- sanet / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('05a7c7eb-c69a-4738-afdc-f54e1e9f088c', 'valdip503@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Valdimira', 'Pereira', 'valdimira', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- valdimira / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e7e71d19-dbbd-4874-b9dc-7899c09926a1', 'mdlalosebeatrice@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Beatrice Salome', 'Ramoshaba', 'beatrice', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- beatrice / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('bf6a5669-fc6b-4a85-a0a0-51443c350879', 'shezib399@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Bongiwe', 'Shezi', 'bongiwe', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- bongiwe / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('09c5cef2-7a86-4b78-a5f3-60b5a07c5e46', 'natashashiba7@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Nompumelelo Natasha', 'Shiba', 'nompumelelo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- nompumelelo / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('57e3fa60-41a2-4271-b3ef-37cc3b5e7753', 'shobamthobisi085@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Mthobisi', 'Shoba', 'mthobisi', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- mthobisi / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('de9ab8b0-4456-4afa-a26d-f48d6c13ab88', 'vundlavusumuzi46@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Vusumuzi Brian', 'Vundla', 'vusi', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- vusi / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('529d3f2d-eb7b-44f6-ad4b-54961b2f135d', 'siyabongavezuthando@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Siyabonga', 'Zulu', 'siyabonga', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '2'); -- siyabonga / BitDenver
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('17bff3c1-e8f0-403f-8c5a-776ef8fd2a2e', 'wtc@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Wardson Tapiwa', 'Chikuruwo', 'wardson', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a2ad8f4a-9ed2-4048-b531-89da6883f9e0'); -- wardson / BitHarare
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('57e4d3b9-0dc7-4fa5-83ff-5a43abb1b57d', 'shavitakunda@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Takunda', 'Shavi', 'takunda', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a2ad8f4a-9ed2-4048-b531-89da6883f9e0'); -- takunda / BitHarare
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('7be568aa-92f6-4631-91e9-87186e4b24f8', 'ziedawu@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Zibusiso', 'sibanda', 'zibusiso', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a2ad8f4a-9ed2-4048-b531-89da6883f9e0'); -- zibusiso / BitHarare
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('aaf031f6-1fd2-407a-9cb6-6c593e408587', 'lorenzomaskew@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Lorenzo Thabang', 'Maskew', 'lorenzo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '68b3ac03-6906-4466-97fa-9c9c92ff0957'); -- lorenzo / BitWitbank
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('6d429caf-2cea-4d29-b32f-9a8fd12c6472', 'josephchingembo@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Joseph', 'Chingembo', 'joseph', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '87d7fd91-9550-4ec7-873b-2139c5f95f31'); -- joseph / BitLusaka
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('5c6785d5-4751-400b-a2a6-d2e9d75027ff', 'eliaskunda@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Elias', 'Kunda', 'alick', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '87d7fd91-9550-4ec7-873b-2139c5f95f31'); -- alick / BitLusaka
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('640d6583-7cfe-42a6-bb62-2a298a2384e7', 'kenneth.mukumba@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Kenneth', 'Mukumba', 'kenny', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '87d7fd91-9550-4ec7-873b-2139c5f95f31'); -- kenny / BitLusaka
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('5591dd0a-4023-4768-a416-f25e919d9606', 'faisonmillion@icloud.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Faison', 'Million', 'faison', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '54391e47-c7ef-47d0-8f4d-8e45f20bf3d0'); -- faison / BitBoksburg
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('c9e3d53e-94b8-4abd-8b2c-fee10f404c3e', 'nkululeko@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Nkululeko Lewele', 'Ndlovu', 'nkululeko', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '30c19866-7ef5-4dcc-89f3-33f265146d31'); -- nkululeko / BitBronkhortspruit
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('bd43d80a-d193-4a95-b9ba-21ef103ccc63', 'mo@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Mogau', 'Baloi', 'mogau', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '06889faa-fc18-41f3-a186-6396fa7defca'); -- mogau / BitBurgersfort
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('5a40eaeb-80ef-4fca-9b7a-6bd5d8803c3f', 'chedzabatsho@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Chedza Batsho James', 'James', 'chedza', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a737ebc9-2d08-47c6-892a-ffa2c2989ea0'); -- chedza / BitFrancistown
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('81b76034-c73d-4661-b7d9-ae38dadbcc4e', 'oratilekakgamatso@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Oratile', 'Kgakgamatso', 'oratile', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a737ebc9-2d08-47c6-892a-ffa2c2989ea0'); -- oratile / BitFrancistown
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('7fa52b78-9287-4a2e-a2f8-1521df9dd694', 'kheu@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Kheu', 'Mokganedi', 'kheu', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'a737ebc9-2d08-47c6-892a-ffa2c2989ea0'); -- kheu / BitFrancistown
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('8680d6f3-2d66-43d0-83b8-db97b2af885f', 'edwinahc83@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Edwina Heloise', 'Cornelius', 'edwina', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'e951e09e-4516-4a3c-a04b-a03ef3d9023e'); -- edwina / BitGeorge
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('2a04a4d5-7877-439b-a0cc-6a340df12d40', 'anathi@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Anathi', 'Malikiti', 'anathi', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'e951e09e-4516-4a3c-a04b-a03ef3d9023e'); -- anathi / BitGeorge
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('11361c29-f8ea-47bf-a3df-e7ac4da337a2', 'ephraim@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Ephraim', 'Ngqukudu', 'ephraim', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'e951e09e-4516-4a3c-a04b-a03ef3d9023e'); -- ephraim / BitGeorge
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('a26a1093-002f-470f-be82-7d4136d33577', 'fernando@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Fernando Moises', 'Guambe', 'fernando', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '66395da2-3cc9-4e4d-8e02-53707d54702d'); -- fernando / GIPTEC Maputo
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('4476f3ae-f779-4b3d-b829-b6b8e354e574', 'eugenio.miambo@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Eugenio Marcos', 'Miambo', 'eugenio', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '66395da2-3cc9-4e4d-8e02-53707d54702d'); -- eugenio / GIPTEC Maputo
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('057e4b7e-c0ba-4c07-b369-eb356e5f71bb', 'rafael.uaiene@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Rafael Paulo', 'Uaiene', 'rafael', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'fd80a488-e831-4229-8cfe-5c344494c606'); -- rafael / GIPTEC Matola
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e7ff2ca0-5e5a-4e67-b204-eb63672bf2cc', 'gilberto@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Gilberto Sara', 'Zandamela', 'gilberto', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'fd80a488-e831-4229-8cfe-5c344494c606'); -- gilberto / GIPTEC Matola
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('0a26afb4-4c74-4591-8e65-8a0fbc0b9e60', 'sergio@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Sergio', 'Dimande', 'sergio', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'ff76f348-5685-4dc8-8061-68a6e06552f5'); -- sergio / GIPTEC Xai Xai
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('80fde40f-d226-4b59-93c1-da8a95e6c858', 'jaime@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Jaime Alberto', 'Mabjaia', 'jaime', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5d0aaf7c-325b-406c-8b5b-b6403a406b0f'); -- jaime / GIPTEC Zimpeto
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('9456e754-02ac-43af-b59d-de306a7b53fb', 'vieira@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Vieira Sergio', 'Manhique', 'vieira', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5d0aaf7c-325b-406c-8b5b-b6403a406b0f'); -- vieira / GIPTEC Zimpeto
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('f51b9bdd-b83d-4e31-ac59-f47d64e78408', 'ernesto@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Ernesto Armindo', 'Nhanombe', 'ernesto', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5d0aaf7c-325b-406c-8b5b-b6403a406b0f'); -- ernesto / GIPTEC Zimpeto
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('7295d2d8-12ef-4fe0-a81b-dd329a38ae1e', 'paulo@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Paulo Maximiano', 'Sitoe', 'paulo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5d0aaf7c-325b-406c-8b5b-b6403a406b0f'); -- paulo / GIPTEC Zimpeto
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('acad52d3-5cd6-4af4-8074-ef77a7369874', 'nduvhonemutudi@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Thiambi Edcan', 'Mushadu', 'thiambi', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'fedb3796-a73f-4549-bf01-36fea1cfaa53'); -- thiambi / BitGiyani
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('9d3b8db2-f188-45dc-958a-e9976528b46c', 'magadagelaml@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Mpho', 'Magadagela', 'mpho', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '193867ca-53a2-476c-81ef-44ffb68ab0f1'); -- mpho / BitLouisTrichardt
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('c3ec2d93-8fe3-4608-a0ce-d651586e196d', 'mosalaking6@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Boitshwaro', 'Mosalashuping', 'boitshwaro', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b12e38da-4e84-4cc7-bcb8-9b36695aeb04'); -- boitshwaro / BitMafikeng
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('348a08f1-a2cc-4dc6-85bb-b200c0511f00', 'kgaugelo@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Kgaugelo', 'Jene', 'kgaugelo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '48ce30a1-7991-4b0b-b538-569c128a9d6e'); -- kgaugelo / BitMokopane
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('a40201bb-7145-4a34-83ae-457637598caa', 'mabathamelvin@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Melvin', 'Mabatha', 'melvinm', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '1363d96e-86e1-467a-ad6b-3b0cda255223'); -- melvinm / Bitnelspruit
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('6c46f81c-383a-4113-a408-d27028bdd4dd', 'fransndhlovu27@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Frans', 'Ndhlovu', 'frans', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '1363d96e-86e1-467a-ad6b-3b0cda255223'); -- frans / Bitnelspruit
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('b6ae383f-1548-4968-be09-ceebcfffa92c', 'stiga.raphasha@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Nditsheni Stiga', 'Raphasha', 'stiga', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '1363d96e-86e1-467a-ad6b-3b0cda255223'); -- stiga / Bitnelspruit
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('6663a317-51fe-4ec5-a6e4-ac49fd746a60', 'mafunisac1@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Christopher', 'Mafunisa', 'chris', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b29610c2-0a79-4c3f-945e-31f6f1ee022e'); -- chris / BitPolokwane
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('3bc34f2c-701a-4bb3-9b2b-86b446b86bef', 'jm@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Johannes Mereyathaba', 'Malatjii', 'jmalatji', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b29610c2-0a79-4c3f-945e-31f6f1ee022e'); -- jmalatji / BitPolokwane
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('0b051b07-7a21-4cda-acd2-2850c7e51f34', 'JOHANNESBITDRYWALL@GMAIL.COM', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Johannes', 'Mphoka', 'jmphoka', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b29610c2-0a79-4c3f-945e-31f6f1ee022e'); -- jmphoka / BitPolokwane
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('95c98a1e-fff4-437b-a412-225ed3e18ad0', 'rallelema@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Malekutu Agreement', 'Rallele', 'malekutu', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b29610c2-0a79-4c3f-945e-31f6f1ee022e'); -- malekutu / BitPolokwane
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('d1032f31-3da8-474a-ada4-3f3e3060d904', 'nathan.coetzee@bitgroup.co.za', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Nathan', 'Coetzee', 'nathan', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '95d71f0e-d267-4aab-87ca-6307df887e4c'); -- nathan / BitPE
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('dcccb744-e2fc-4284-a615-5ad28b3bf4b8', 'maxnyiki@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Mthobeli Maxwell', 'Nyiki', 'maxwell', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '95d71f0e-d267-4aab-87ca-6307df887e4c'); -- maxwell / BitPE
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e6833cb7-cbd8-47a5-9df4-5f3cd3a0ac7b', 'calvinlindeque4@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Calvin', 'Lindeque', 'calvin', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b298e2b0-c8f6-427d-88a3-a047aea7da4c'); -- calvin / BitRandfontein
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('065b9332-7c84-41a4-840b-956b94d999f5', 'vanlouwebennet@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Bennet', 'van louwe', 'bennet', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'b298e2b0-c8f6-427d-88a3-a047aea7da4c'); -- bennet / BitRandfontein
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('e4cdf7d8-566b-4000-9e02-d962be141b5f', 'ksn@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Katlego Success', 'Ngolobe', 'katlego', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '9299084b-1777-4214-9af3-3d5158e91e7e'); -- katlego / BitRustenburg
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('89bc4181-92fa-4874-be27-0a0448b9dfd9', 'masinalindy1@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Lindokuhle Charity', 'Masina', 'lindy', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5de01bbf-d469-4b7b-b325-02cf2b986004'); -- lindy / BitSouthGate
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('06a5f07c-e6a5-4a17-af5a-ad016b81bf0b', 'thabisomazibuko718@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Thabiso', 'Mazibuko', 'thabiso', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '5de01bbf-d469-4b7b-b325-02cf2b986004'); -- thabiso / BitSouthGate
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('148c1c7e-6284-4667-8fe3-034a562cacff', 'israelbalexxx@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Ipfi', 'Bale', 'ipfi', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', 'ff87c43a-42f9-4781-b472-204ba80a6bfd'); -- ipfi / BitThohoyandou
INSERT INTO users (id, email, password, firstName, lastName, username, role, emailVerified, status, createdAt, updatedAt, avatarId, orgIdId, branchIdId) VALUES ('f0e4082f-17dc-442a-a51e-3f6030625258', 'matlou7188@gmail.com', '$2b$12$qA7D8XsL.gO0i/CRM94Hk.tczuiBsA8yztDX0se6mv1SrKGauYQTK', 'Tshepo', 'Madou', 'tshepo', 'user', 0, 'active', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), NULL, '2', '016e4cd7-8ff0-4d83-83db-3594490e4919'); -- tshepo / BitTzaneen

-- COMMIT;
-- ROLLBACK;

-- Username updates: 37
-- Total inserts: 84
